# node-stage
FROM node:18.13.0 as builder

WORKDIR '/usr/src/app'

COPY package.json .
COPY package-lock.json ./

COPY ./ ./

RUN npm install -f
RUN npm run build

# nginx-stage
FROM nginx:1.13
EXPOSE 80

RUN rm /etc/nginx/conf.d/default.conf
COPY ./confs/nginx-local.conf /etc/nginx/conf.d

RUN rm /usr/share/nginx/html/index.html
COPY --from=builder /usr/src/app/build /usr/share/nginx/html